# Generated by Django 4.0.6 on 2022-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Progress',
            field=models.CharField(choices=[('Now', 'Now'), ('Review', 'Review')], default='Pending', max_length=150),
        ),
    ]
