# Generated by Django 4.0.6 on 2022-08-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_topic_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Progress',
            new_name='status',
        ),
    ]
