# Generated by Django 4.0.6 on 2022-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_progress_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Now', 'Now'), ('Review', 'Review')], default='Now', max_length=150),
        ),
    ]
