# Generated by Django 4.0.6 on 2022-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_topic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('status', models.CharField(choices=[('Now', 'Now'), ('Review', 'Review')], default='Review', max_length=150)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
    ]
