# Generated by Django 4.0.6 on 2022-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_previous_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous_topic',
            name='End_date',
        ),
    ]
