# Generated by Django 4.0.6 on 2022-08-15 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_attenndance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attenndance',
            new_name='Attendance',
        ),
    ]
