# Generated by Django 4.0.6 on 2022-08-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
            preserve_default=False,
        ),
    ]
