# Generated by Django 4.0.6 on 2022-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_report_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Department',
        ),
    ]
