# Generated by Django 4.0.6 on 2022-08-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='FROM',
            new_name='From',
        ),
    ]
